---
- name: present groups
  group: name="{{item.name}}" gid="{{item.id}}"
  with_items: groups_present
  tags: ['users','groups','configuration']

- name: per-user group create
  group: name="{{item.name}}" gid="{{item.id}}"
  with_items: users
  when: users_create_per_user_group
  tags: ['users','configuration']

- name: present users
  user: name="{{item.name}}"
        group="{{item.name if users_create_per_user_group
            else users_group}}"
        groups="{{item.groups | join(',')}}"
        shell={{item.shell if item.shell is defined else users_default_shell}}
        password="{{item.password if item.password is defined else '!'}}"
        comment="{{item.comment}}"
        uid="{{item.id}}"
        createhome="{{'yes' if users_create_homedirs else 'no'}}"
  with_items: users
  tags: ['users','configuration']

- name: ssh keys
  authorized_key: user="{{item.0.name}}" key="{{item.1}}"
  with_subelements:
    - users
    - ssh_key
  tags: ['users','configuration']

- name: absent users
  user: name="{{item.name}}" state=absent
  with_items: users_absent
  tags: ['users','configuration']

- name: per-user absent groups
  group: name="{{item.name}}" state=absent
  with_items: users_absent
  when: users_create_per_user_group
  tags: ['users','configuration']
